### PR TITLE
Version Bump

### PR DESCRIPTION
**Pull request by ryanmaclean**
Things are happening! (sorry, we caught this during today's training)

### CODE REVIEW

**Comment by chzbrgr71** [comment]
What is this? A center for ants?!

**Comment by chzbrgr71** [comment]
this looks good. thanks!

**Comment by ryanmaclean** [comment]
"Our PRs need to be _at least_ this big!" @chzbrgr71  ❤️

**Comment by snpdev** [comment]
FWIW, 1.11.6 is not supported in my "Visual Studio Enterprise – MPN" subscription. 1.11.5 works.
```
michael@Azure:~$ az aks create -n $CLUSTERNAME -g $RGNAME -k 1.11.6 \
> --service-principal $APPID \
> --client-secret $CLIENTSECRET \
> --generate-ssh-keys -l $LOCATION \
> --node-count 3 \
> --enable-addons http_application_routing,monitoring
Operation failed with status: 'Bad Request'. Details: The value of parameter orchestratorProfile.OrchestratorVersion is invalid.
```
```
michael@Azure:~$ az aks get-versions --location eastus --output table
KubernetesVersion    Upgrades
-------------------  ----------------------
1.11.5               None available
1.11.4               1.11.5
1.10.9               1.11.4, 1.11.5
1.10.8               1.10.9, 1.11.4, 1.11.5
1.9.11               1.10.8, 1.10.9
1.9.10               1.9.11, 1.10.8, 1.10.9
1.8.15               1.9.10, 1.9.11
1.8.14               1.8.15, 1.9.10, 1.9.11
```
```
michael@Azure:~$ az aks create -n $CLUSTERNAME -g $RGNAME -k 1.11.5 --service-principal $APPID --client-secret $CLIENTSECRET --generate-ssh-keys -l $LOCATION --node-count 3 --enable-addons http_application_routing,monitoring
 - Running ..
```

**Pull request merged**
